version: "3.9"

networks:
  rabbitmq-server-network:
    name: rabbitmq-server-network
    driver: bridge

services:
  # rabbitmq-server:
  #   build: .
  #   image: rabbitmq-server:latest
  #   container_name: rabbitmq-server
  #   environment:
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - ${PWD}:/app
  #     - "/etc/timezone:/etc/timezone:ro"
  #     - "/etc/localtime:/etc/localtime:ro"
  #   networks:
  #     - rabbitmq-server-network
  #   restart: on-failure
  #   depends_on:
  #     - rabbitmq
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - rabbitmq-server-network
    ports:
      - 5672:5672
      - 15672:15672
